In [1]:
import os
import os.path as osp
import shutil
import meshio
from typing import List

In [2]:
from mesh_handler import xdmf_to_meshes, meshes_to_xdmf, vtu_to_mesh, mesh_to_vtu, accessing_mesh_data, create_mock_mesh

In [3]:
# DEMO
print("\n### DEMO  XDMF ARCHIVE ###")
print("2D mesh archive:")
xdmf_path = osp.join(os.getcwd(), "Obstacle.xdmf")
meshes = xdmf_to_meshes(xdmf_path)
meshes[0].points


### DEMO  XDMF ARCHIVE ###
2D mesh archive:
Loaded 121 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\Obstacle.xdmf



array([[0.      , 0.      , 0.      ],
       [4.      , 0.      , 0.      ],
       [4.      , 3.      , 0.      ],
       ...,
       [2.20449 , 0.663779, 0.      ],
       [3.82059 , 2.75713 , 0.      ],
       [0.736707, 0.299932, 0.      ]], shape=(1632, 3), dtype=float32)

In [4]:
accessing_mesh_data(meshes[10])

There are 1632 nodes in this mesh.
First 5 nodes of the mesh: 
[[0.  0.  0. ]
 [4.  0.  0. ]
 [4.  3.  0. ]
 [0.  3.  0. ]
 [0.  2.9 0. ]] 

Types of cells in the mesh: ['triangle']
There are 3122 triangular cells in this mesh.
First 5 triangular cells of the mesh: 
[[ 696 1561  561]
 [ 642  252 1464]
 [ 252  605 1464]
 [ 275  652 1555]
 [1322  664  604]] 

Feature name: Vitesse / Feature shape: (1632, 3)
Feature name: Pression / Feature shape: (1632,)


In [5]:
print("\n3D mesh archive:")
xdmf_path = osp.join(os.getcwd(), "AllFields_Resultats_MESH_1.xdmf")
meshes = xdmf_to_meshes(xdmf_path)
accessing_mesh_data(meshes[10])


3D mesh archive:
Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\AllFields_Resultats_MESH_1.xdmf

There are 11446 nodes in this mesh.
First 5 nodes of the mesh: 
[[-2.205367   4.560882   1.67214  ]
 [-2.2580128  4.7989006  1.8012575]
 [-2.212806   5.078872   1.8893555]
 [-2.0400388  5.2704096  1.920871 ]
 [-1.8397863  5.4581513  1.9444325]] 

Types of cells in the mesh: ['tetra']
There are 55472 tetrahedral cells in this mesh.
First 5 tetrahedral cells of the mesh: 
[[4803 4804 4805 4806]
 [4807    0 2921 2922]
 [4808 1941 4809 4810]
 [4811 4812 4813 4814]
 [4815 3583 4816    3]] 

Feature name: Vitesse / Feature shape: (11446, 3)
Feature name: Pression / Feature shape: (11446,)


In [6]:
mesh = meshes[0]
mesh.cells_dict['tetra']

array([[4803, 4804, 4805, 4806],
       [4807,    0, 2921, 2922],
       [4808, 1941, 4809, 4810],
       ...,
       [6558, 6354, 6587, 6804],
       [6176, 6908, 9039, 6943],
       [6176, 5669, 7795, 6178]], shape=(55472, 4))

In [7]:
def get_neighbors(mesh, cell_idx):
    neighbors = set()
    for i, cell in enumerate(mesh.cells_dict['tetra']):
        if cell_idx in cell:
            # the cell is in this tetrahedron
            for j in cell:
                if j != cell_idx:
                    neighbors.add(j.item())
    return neighbors

mesh = meshes[0]
get_neighbors(mesh, 50)

{49, 51, 801, 3253, 3433, 3434, 6748, 9626, 10349}

In [8]:
print("\n### DEMO  VTU FILE FORMAT ###")
mock_mesh = create_mock_mesh()
vtu_path = osp.join(os.getcwd(), "mock_mesh.vtu")
mesh_to_vtu(mock_mesh, vtu_path)


### DEMO  VTU FILE FORMAT ###
Mock mesh created.
Mesh saved to c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\mock_mesh.vtu


# Real data

In [9]:
# get list of .xdmf files
# keep only the .xdmf files
list_files = os.listdir(osp.join(os.getcwd(), "4Students_AnXplore03"))
list_files = [f for f in list_files if f.endswith('.xdmf')]

array_meshes = []
for f in list_files[:5]:
    # print("\n\n New file:\n")
    xdmf_path = osp.join(os.getcwd(), "4Students_AnXplore03", f)
    meshes = xdmf_to_meshes(xdmf_path)
    array_meshes.append(meshes)

print(len(array_meshes), len(array_meshes[0]))

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_1.xdmf

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_11.xdmf

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_117.xdmf

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_119-1.xdmf

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_119-2.xdmf

5 80


In [10]:
xdmf_path = osp.join(os.getcwd(), "4Students_AnXplore03/AllFields_Resultats_MESH_1.xdmf")
meshes = xdmf_to_meshes(xdmf_path)
accessing_mesh_data(meshes[10])

Loaded 80 timesteps from AllFields_Resultats_MESH_1.xdmf

There are 11446 nodes in this mesh.
First 5 nodes of the mesh: 
[[-2.205367   4.560882   1.67214  ]
 [-2.2580128  4.7989006  1.8012575]
 [-2.212806   5.078872   1.8893555]
 [-2.0400388  5.2704096  1.920871 ]
 [-1.8397863  5.4581513  1.9444325]] 

Types of cells in the mesh: ['tetra']
There are 55472 tetrahedral cells in this mesh.
First 5 tetrahedral cells of the mesh: 
[[4803 4804 4805 4806]
 [4807    0 2921 2922]
 [4808 1941 4809 4810]
 [4811 4812 4813 4814]
 [4815 3583 4816    3]] 

Feature name: Vitesse / Feature shape: (11446, 3)
Feature name: Pression / Feature shape: (11446,)


# Create train dataset

In [11]:
import numpy as np
import scipy.sparse as sp
import tqdm
import meshio
import torch
from torch_geometric.data import Data

In [91]:
mesh = meshes[0]
mesh.cells_dict['tetra']
def get_adjacency_matrix(mesh):
    n_cells = len(mesh.cells_dict['tetra'])
    # adjacency matrix is a sparse matrix
    adj_matrix = sp.lil_matrix((len(mesh.points), len(mesh.points)), dtype=int)
    for i in tqdm.tqdm(range(n_cells)):
        # print(f"Cell {i}/{n_cells}")
        cell = mesh.cells_dict['tetra'][i]
        for n1 in cell:
            for n2 in cell:
                if n1 != n2:
                    adj_matrix[n1, n2] = 1
    return adj_matrix

adj_matrix = get_adjacency_matrix(mesh)
adj_matrix

100%|██████████| 55472/55472 [00:21<00:00, 2577.82it/s]


<List of Lists sparse matrix of dtype 'int64'
	with 143436 stored elements and shape (11446, 11446)>

In [12]:
def get_geometric_data(mesh):
    # Extract node positions
    node_positions = mesh.points  # Shape: (num_nodes, 3)

    # Extract connectivity (edges)
    elements = mesh.cells_dict["tetra"]  # Extract tetrahedra

    # Convert elements to edges (each triangle/tetrahedron defines connections)
    edges = np.hstack([
            [elements[:, 0], elements[:, 1]],  # Edge 1
            [elements[:, 0], elements[:, 2]],  # Edge 2
            [elements[:, 0], elements[:, 3]],  # Edge 3
            [elements[:, 1], elements[:, 2]],  # Edge 4
            [elements[:, 1], elements[:, 3]],  # Edge 5
            [elements[:, 2], elements[:, 3]],  # Edge 6
        ]).T # Shape: (num_edges, 2)

    edges = np.unique(edges, axis=0)  # Remove duplicate edges
    edge_index = torch.tensor(edges.T, dtype=torch.long)  # PyG format (2, num_edges)

    # Compute edge features (relative positions)
    edge_attr = node_positions[edges[:, 1]] - node_positions[edges[:, 0]]  # Shape: (num_edges, 3)
    edge_attr = torch.tensor(edge_attr, dtype=torch.float)
    return edge_index, edge_attr

In [20]:
# we will train the model with times t-2 and t-1 to predict t
# for each point, we can predict vx, vy, vz and p using the previous time steps

def build_data():
    data = {
        'features' : [],
        'target' : []
    }
    list_files = os.listdir(osp.join(os.getcwd(), "4Students_AnXplore03"))
    list_files = [f for f in list_files if f.endswith('.xdmf')]

    for f in tqdm.tqdm(list_files):
        # print("\n\n New file:\n")
        xdmf_path = osp.join(os.getcwd(), "4Students_AnXplore03", f)
        meshes = xdmf_to_meshes(xdmf_path)
        mesh = meshes[0]

        edge_index, edge_attr = get_geometric_data(mesh)

        for time_step in range(2, len(meshes)):
            # Create node features (x, y, z, vx, vy, vz, p)
            node_features_1 = np.hstack([
                meshes[time_step-1].points,
                meshes[time_step-1].point_data['Vitesse'],
                meshes[time_step-1].point_data['Pression'].reshape(-1, 1)
            ]) # Shape: (num_nodes, 7)
            node_features = np.hstack([
                meshes[time_step].points,
                meshes[time_step].point_data['Vitesse'],
                meshes[time_step].point_data['Pression'].reshape(-1, 1)
            ]) # Shape: (num_nodes, 7)

            # Create PyTorch Geometric data object
            graph_data_1 = Data(x=node_features_1, edge_index=edge_index, edge_attr=edge_attr)
            graph_data = Data(x=node_features, edge_index=edge_index, edge_attr=edge_attr)

            data['features'].append(graph_data_1)
            data['target'].append(graph_data)
    return data

In [21]:
data = build_data()

  0%|          | 0/103 [00:00<?, ?it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_1.xdmf



  1%|          | 1/103 [00:00<00:55,  1.83it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_11.xdmf



  2%|▏         | 2/103 [00:01<01:17,  1.30it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_117.xdmf



  3%|▎         | 3/103 [00:02<01:11,  1.39it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_119-1.xdmf



  4%|▍         | 4/103 [00:02<01:01,  1.61it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_119-2.xdmf



  5%|▍         | 5/103 [00:03<00:55,  1.76it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_120.xdmf



  6%|▌         | 6/103 [00:03<01:01,  1.58it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_121.xdmf



  7%|▋         | 7/103 [00:04<00:56,  1.69it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_128.xdmf



  8%|▊         | 8/103 [00:05<01:02,  1.52it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_129.xdmf



  9%|▊         | 9/103 [00:05<00:58,  1.61it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_134.xdmf



 10%|▉         | 10/103 [00:06<00:55,  1.67it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_135.xdmf



 11%|█         | 11/103 [00:06<00:54,  1.68it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_136.xdmf



 12%|█▏        | 12/103 [00:07<00:54,  1.67it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_137.xdmf



 13%|█▎        | 13/103 [00:08<00:55,  1.63it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_138.xdmf



 14%|█▎        | 14/103 [00:08<00:55,  1.61it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_139.xdmf



 15%|█▍        | 15/103 [00:09<00:56,  1.55it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_140.xdmf



 16%|█▌        | 16/103 [00:10<00:58,  1.48it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_142.xdmf



 17%|█▋        | 17/103 [00:10<00:54,  1.57it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_144-2.xdmf



 17%|█▋        | 18/103 [00:11<00:54,  1.56it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_148.xdmf



 18%|█▊        | 19/103 [00:11<00:52,  1.61it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_151.xdmf



 19%|█▉        | 20/103 [00:12<00:54,  1.53it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_152.xdmf



 20%|██        | 21/103 [00:13<00:53,  1.54it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_153.xdmf



 21%|██▏       | 22/103 [00:13<00:52,  1.53it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_155.xdmf



 22%|██▏       | 23/103 [00:14<00:52,  1.53it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_157.xdmf



 23%|██▎       | 24/103 [00:15<00:49,  1.60it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_158.xdmf



 24%|██▍       | 25/103 [00:15<00:51,  1.52it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_159.xdmf



 25%|██▌       | 26/103 [00:16<00:50,  1.53it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_161.xdmf



 26%|██▌       | 27/103 [00:17<00:48,  1.56it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_162.xdmf



 27%|██▋       | 28/103 [00:17<00:48,  1.56it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_163-1.xdmf



 28%|██▊       | 29/103 [00:18<00:47,  1.57it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_163-2.xdmf



 29%|██▉       | 30/103 [00:19<00:46,  1.58it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_164.xdmf



 30%|███       | 31/103 [00:19<00:45,  1.57it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_165.xdmf



 31%|███       | 32/103 [00:20<00:53,  1.34it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_166.xdmf



 32%|███▏      | 33/103 [00:21<00:51,  1.35it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_168-1.xdmf



 33%|███▎      | 34/103 [00:22<00:53,  1.28it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_168-2.xdmf



 34%|███▍      | 35/103 [00:22<00:50,  1.35it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_170.xdmf



 35%|███▍      | 36/103 [00:23<00:47,  1.42it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_171.xdmf



 36%|███▌      | 37/103 [00:25<01:06,  1.01s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_172.xdmf



 37%|███▋      | 38/103 [00:26<01:05,  1.00s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_173.xdmf



 38%|███▊      | 39/103 [00:26<00:57,  1.12it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_174.xdmf



 39%|███▉      | 40/103 [00:27<00:51,  1.21it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_175.xdmf



 40%|███▉      | 41/103 [00:28<00:46,  1.34it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_177.xdmf



 41%|████      | 42/103 [00:28<00:46,  1.31it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_178.xdmf



 42%|████▏     | 43/103 [00:29<00:47,  1.27it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_180.xdmf



 43%|████▎     | 44/103 [00:30<00:46,  1.27it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_181.xdmf



 44%|████▎     | 45/103 [00:31<00:44,  1.31it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_182-1.xdmf



 45%|████▍     | 46/103 [00:32<00:42,  1.33it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_182-2.xdmf



 46%|████▌     | 47/103 [00:32<00:39,  1.41it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_182-3.xdmf



 47%|████▋     | 48/103 [00:33<00:36,  1.50it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_183.xdmf



 48%|████▊     | 49/103 [00:33<00:34,  1.55it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_185.xdmf



 49%|████▊     | 50/103 [00:34<00:32,  1.63it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_186-1.xdmf



 50%|████▉     | 51/103 [00:35<00:33,  1.57it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_186-2.xdmf



 50%|█████     | 52/103 [00:35<00:32,  1.57it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_187.xdmf



 51%|█████▏    | 53/103 [00:36<00:37,  1.34it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_188.xdmf



 52%|█████▏    | 54/103 [00:37<00:39,  1.25it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_189.xdmf



 53%|█████▎    | 55/103 [00:38<00:34,  1.37it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_19.xdmf



 54%|█████▍    | 56/103 [00:38<00:32,  1.44it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_191.xdmf



 55%|█████▌    | 57/103 [00:39<00:33,  1.39it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_192.xdmf



 56%|█████▋    | 58/103 [00:40<00:34,  1.32it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_193-1.xdmf



 57%|█████▋    | 59/103 [00:41<00:36,  1.21it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_193-2.xdmf



 58%|█████▊    | 60/103 [00:42<00:42,  1.02it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_194.xdmf



 59%|█████▉    | 61/103 [00:44<00:47,  1.14s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_195.xdmf



 60%|██████    | 62/103 [00:47<01:08,  1.66s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_196-1.xdmf



 61%|██████    | 63/103 [00:47<00:56,  1.41s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_196-2.xdmf



 62%|██████▏   | 64/103 [00:50<01:06,  1.71s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_197.xdmf



 63%|██████▎   | 65/103 [00:52<01:13,  1.94s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_198-1.xdmf



 64%|██████▍   | 66/103 [00:56<01:30,  2.45s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_198-2.xdmf



 65%|██████▌   | 67/103 [00:58<01:25,  2.38s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_199.xdmf



 66%|██████▌   | 68/103 [01:00<01:18,  2.25s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_2.xdmf



 67%|██████▋   | 69/103 [01:01<01:01,  1.81s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_200.xdmf



 68%|██████▊   | 70/103 [01:04<01:13,  2.24s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_202.xdmf



 69%|██████▉   | 71/103 [01:05<00:58,  1.83s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_203.xdmf



 70%|██████▉   | 72/103 [01:06<00:50,  1.63s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_204.xdmf



 71%|███████   | 73/103 [01:08<00:51,  1.70s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_205.xdmf



 72%|███████▏  | 74/103 [01:09<00:43,  1.51s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_206.xdmf



 73%|███████▎  | 75/103 [01:10<00:38,  1.39s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_207.xdmf



 74%|███████▍  | 76/103 [01:11<00:35,  1.33s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_208.xdmf



 75%|███████▍  | 77/103 [01:13<00:33,  1.31s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_209.xdmf



 76%|███████▌  | 78/103 [01:14<00:30,  1.21s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_210.xdmf



 77%|███████▋  | 79/103 [01:15<00:26,  1.11s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_211.xdmf



 78%|███████▊  | 80/103 [01:15<00:23,  1.01s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_212.xdmf



 79%|███████▊  | 81/103 [01:16<00:21,  1.02it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_213.xdmf



 80%|███████▉  | 82/103 [01:17<00:19,  1.05it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_214.xdmf



 81%|████████  | 83/103 [01:18<00:18,  1.10it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_215.xdmf



 82%|████████▏ | 84/103 [01:19<00:17,  1.10it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_217.xdmf



 83%|████████▎ | 85/103 [01:20<00:20,  1.14s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_219.xdmf



 83%|████████▎ | 86/103 [01:21<00:17,  1.03s/it]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_23.xdmf



 84%|████████▍ | 87/103 [01:22<00:15,  1.05it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_25.xdmf



 85%|████████▌ | 88/103 [01:23<00:14,  1.06it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_26.xdmf



 86%|████████▋ | 89/103 [01:24<00:12,  1.10it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_28.xdmf



 87%|████████▋ | 90/103 [01:25<00:11,  1.16it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_3.xdmf



 88%|████████▊ | 91/103 [01:26<00:11,  1.02it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_31.xdmf



 89%|████████▉ | 92/103 [01:27<00:10,  1.07it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_34.xdmf



 90%|█████████ | 93/103 [01:27<00:09,  1.11it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_40.xdmf



 91%|█████████▏| 94/103 [01:28<00:07,  1.15it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_42-1.xdmf



 92%|█████████▏| 95/103 [01:29<00:06,  1.17it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_42-2.xdmf



 93%|█████████▎| 96/103 [01:30<00:06,  1.14it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_42-3.xdmf



 94%|█████████▍| 97/103 [01:31<00:05,  1.18it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_44.xdmf



 95%|█████████▌| 98/103 [01:31<00:03,  1.26it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_54-1.xdmf



 96%|█████████▌| 99/103 [01:32<00:03,  1.30it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_54-2.xdmf



 97%|█████████▋| 100/103 [01:33<00:02,  1.33it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_55.xdmf



 98%|█████████▊| 101/103 [01:34<00:01,  1.28it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_6.xdmf



 99%|█████████▉| 102/103 [01:35<00:00,  1.12it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\aneurysm_project\4Students_AnXplore03\AllFields_Resultats_MESH_9-1.xdmf



100%|██████████| 103/103 [01:36<00:00,  1.07it/s]


In [16]:
data['features'][0]

Data(x=[11446, 7], edge_index=[2, 110854], edge_attr=[110854, 3])

In [17]:
data['target'][0]

Data(x=[11446, 7], edge_index=[2, 110854], edge_attr=[110854, 3])

In [18]:
data.keys()

dict_keys(['features', 'target'])

In [19]:
# get length of the data
len(data['features'])

234

# Message passing model

In [ ]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import MessagePassing
from torch_geometric.utils import add_self_loops

class FluidGNNLayer(MessagePassing):
    def __init__(self, in_channels, out_channels):
        super(FluidGNNLayer, self).__init__(aggr='mean')  # Mean aggregation
        self.edge_mlp = torch.nn.Sequential(
            torch.nn.Linear(in_channels * 2 + 3, 64),  # Edge MLP (uses node features + relative position)
            torch.nn.ReLU(),
            torch.nn.Linear(64, out_channels)
        )
        self.node_mlp = torch.nn.Sequential(
            torch.nn.Linear(in_channels + out_channels, 64),
            torch.nn.ReLU(),
            torch.nn.Linear(64, out_channels)
        )

    def forward(self, x, edge_index, edge_attr):
        """
        x: Node features (velocities, pressure, positions) [num_nodes, in_channels]
        edge_index: Connectivity [2, num_edges]
        edge_attr: Edge features (relative positions) [num_edges, 3]
        """
        edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        return self.propagate(edge_index, x=x, edge_attr=edge_attr)

    def message(self, x_i, x_j, edge_attr):
        """Message function: Computes messages from neighbors."""
        return self.edge_mlp(torch.cat([x_i, x_j, edge_attr], dim=1))

    def update(self, aggr_out, x):
        """Update function: Combines node's previous state with aggregated messages."""
        return self.node_mlp(torch.cat([x, aggr_out], dim=1))


In [ ]:
class FluidGNN(torch.nn.Module):
    def __init__(self, node_features, hidden_dim, output_dim):
        super(FluidGNN, self).__init__()
        self.gnn1 = FluidGNNLayer(node_features, hidden_dim)
        self.gnn2 = FluidGNNLayer(hidden_dim, hidden_dim)
        self.gnn3 = FluidGNNLayer(hidden_dim, output_dim)

    def forward(self, x, edge_index, edge_attr):
        x = F.relu(self.gnn1(x, edge_index, edge_attr))
        x = F.relu(self.gnn2(x, edge_index, edge_attr))
        x = self.gnn3(x, edge_index, edge_attr)  # Output velocity + pressure
        return x


In [ ]:
from torch_geometric.data import Data

# Example data (replace with your real mesh data)
num_nodes = 100
node_features = 7  # [vx, vy, vz, p, x, y, z]
edge_index = torch.randint(0, num_nodes, (2, 300))  # Random edges
x = torch.randn((num_nodes, node_features))  # Random node features
edge_attr = torch.randn((edge_index.size(1), 3))  # Random edge features

# Create PyTorch Geometric data object
graph_data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr)


In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Initialize model
model = FluidGNN(node_features=7, hidden_dim=64, output_dim=4)  # Output: vx, vy, vz, p
model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = torch.nn.MSELoss()

# Training loop
num_epochs = 100
for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()

    # Forward pass
    x_pred = model(graph_data.x.to(device), graph_data.edge_index.to(device), graph_data.edge_attr.to(device))

    # Compute loss (MSE between predicted and true values)
    loss = criterion(x_pred, graph_data.x[:, :4].to(device))  # Target: vx, vy, vz, p

    loss.backward()
    optimizer.step()

    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item():.4f}")
