In [1]:
import os
import os.path as osp
import shutil
import meshio
from typing import List

In [2]:
from mesh_handler import xdmf_to_meshes, meshes_to_xdmf, vtu_to_mesh, mesh_to_vtu, accessing_mesh_data, create_mock_mesh

In [35]:
# DEMO
print("\n### DEMO  XDMF ARCHIVE ###")
print("2D mesh archive:")
xdmf_path = osp.join(os.getcwd(), "Obstacle.xdmf")
meshes = xdmf_to_meshes(xdmf_path)
meshes[0].points


### DEMO  XDMF ARCHIVE ###
2D mesh archive:
Loaded 121 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\Obstacle.xdmf



array([[0.      , 0.      , 0.      ],
       [4.      , 0.      , 0.      ],
       [4.      , 3.      , 0.      ],
       ...,
       [2.20449 , 0.663779, 0.      ],
       [3.82059 , 2.75713 , 0.      ],
       [0.736707, 0.299932, 0.      ]], shape=(1632, 3), dtype=float32)

In [20]:
accessing_mesh_data(meshes[10])

There are 1632 nodes in this mesh.
First 5 nodes of the mesh: 
[[0.  0.  0. ]
 [4.  0.  0. ]
 [4.  3.  0. ]
 [0.  3.  0. ]
 [0.  2.9 0. ]] 

Types of cells in the mesh: ['triangle']
There are 3122 triangular cells in this mesh.
First 5 triangular cells of the mesh: 
[[ 696 1561  561]
 [ 642  252 1464]
 [ 252  605 1464]
 [ 275  652 1555]
 [1322  664  604]] 

Feature name: Vitesse / Feature shape: (1632, 3)
Feature name: Pression / Feature shape: (1632,)


In [43]:
print("\n3D mesh archive:")
xdmf_path = osp.join(os.getcwd(), "AllFields_Resultats_MESH_1.xdmf")
meshes = xdmf_to_meshes(xdmf_path)
accessing_mesh_data(meshes[10])


3D mesh archive:
Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\AllFields_Resultats_MESH_1.xdmf

There are 11446 nodes in this mesh.
First 5 nodes of the mesh: 
[[-2.205367   4.560882   1.67214  ]
 [-2.2580128  4.7989006  1.8012575]
 [-2.212806   5.078872   1.8893555]
 [-2.0400388  5.2704096  1.920871 ]
 [-1.8397863  5.4581513  1.9444325]] 

Types of cells in the mesh: ['tetra']
There are 55472 tetrahedral cells in this mesh.
First 5 tetrahedral cells of the mesh: 
[[4803 4804 4805 4806]
 [4807    0 2921 2922]
 [4808 1941 4809 4810]
 [4811 4812 4813 4814]
 [4815 3583 4816    3]] 

Feature name: Vitesse / Feature shape: (11446, 3)
Feature name: Pression / Feature shape: (11446,)


In [46]:
mesh = meshes[0]
mesh.cells_dict['tetra']

array([[4803, 4804, 4805, 4806],
       [4807,    0, 2921, 2922],
       [4808, 1941, 4809, 4810],
       ...,
       [6558, 6354, 6587, 6804],
       [6176, 6908, 9039, 6943],
       [6176, 5669, 7795, 6178]], shape=(55472, 4))

In [53]:
def get_neighbors(mesh, cell_idx):
    neighbors = set()
    for i, cell in enumerate(mesh.cells_dict['tetra']):
        if cell_idx in cell:
            # the cell is in this tetrahedron
            for j in cell:
                if j != cell_idx:
                    neighbors.add(j.item())
    return neighbors

mesh = meshes[0]
get_neighbors(mesh, 50)

{49, 51, 801, 3253, 3433, 3434, 6748, 9626, 10349}

In [22]:
print("\n### DEMO  VTU FILE FORMAT ###")
mock_mesh = create_mock_mesh()
vtu_path = osp.join(os.getcwd(), "mock_mesh.vtu")
mesh_to_vtu(mock_mesh, vtu_path)


### DEMO  VTU FILE FORMAT ###
Mock mesh created.
Mesh saved to c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\mock_mesh.vtu


# Real data

In [39]:
# get list of .xdmf files
# keep only the .xdmf files
list_files = os.listdir(osp.join(os.getcwd(), "4Students_AnXplore03"))
list_files = [f for f in list_files if f.endswith('.xdmf')]

array_meshes = []
for f in list_files[:5]:
    # print("\n\n New file:\n")
    xdmf_path = osp.join(os.getcwd(), "4Students_AnXplore03", f)
    meshes = xdmf_to_meshes(xdmf_path)
    array_meshes.append(meshes)

print(len(array_meshes), len(array_meshes[0]))

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\4Students_AnXplore03\AllFields_Resultats_MESH_1.xdmf

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\4Students_AnXplore03\AllFields_Resultats_MESH_11.xdmf

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\4Students_AnXplore03\AllFields_Resultats_MESH_117.xdmf

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\4Students_AnXplore03\AllFields_Resultats_MESH_119-1.xdmf

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\4Students_AnXplore03\AllFields_Resultats_MESH_119-2.xdmf

5 80


In [26]:
xdmf_path = osp.join(os.getcwd(), "4Students_AnXplore03/AllFields_Resultats_MESH_1.xdmf")
meshes = xdmf_to_meshes(xdmf_path)
accessing_mesh_data(meshes[10])

Loaded 80 timesteps from AllFields_Resultats_MESH_1.xdmf

There are 11446 nodes in this mesh.
First 5 nodes of the mesh: 
[[-2.205367   4.560882   1.67214  ]
 [-2.2580128  4.7989006  1.8012575]
 [-2.212806   5.078872   1.8893555]
 [-2.0400388  5.2704096  1.920871 ]
 [-1.8397863  5.4581513  1.9444325]] 

Types of cells in the mesh: ['tetra']
There are 55472 tetrahedral cells in this mesh.
First 5 tetrahedral cells of the mesh: 
[[4803 4804 4805 4806]
 [4807    0 2921 2922]
 [4808 1941 4809 4810]
 [4811 4812 4813 4814]
 [4815 3583 4816    3]] 

Feature name: Vitesse / Feature shape: (11446, 3)
Feature name: Pression / Feature shape: (11446,)


# Create train dataset

In [146]:
import numpy as np
import scipy.sparse as sp
import tqdm
import meshio
import torch
from torch_geometric.data import Data

In [91]:
mesh = meshes[0]
mesh.cells_dict['tetra']
def get_adjacency_matrix(mesh):
    n_cells = len(mesh.cells_dict['tetra'])
    # adjacency matrix is a sparse matrix
    adj_matrix = sp.lil_matrix((len(mesh.points), len(mesh.points)), dtype=int)
    for i in tqdm.tqdm(range(n_cells)):
        # print(f"Cell {i}/{n_cells}")
        cell = mesh.cells_dict['tetra'][i]
        for n1 in cell:
            for n2 in cell:
                if n1 != n2:
                    adj_matrix[n1, n2] = 1
    return adj_matrix

adj_matrix = get_adjacency_matrix(mesh)
adj_matrix

100%|██████████| 55472/55472 [00:21<00:00, 2577.82it/s]


<List of Lists sparse matrix of dtype 'int64'
	with 143436 stored elements and shape (11446, 11446)>

In [147]:
def get_geometric_data(mesh):
    # Extract node positions
    node_positions = mesh.points  # Shape: (num_nodes, 3)

    # Extract connectivity (edges)
    elements = mesh.cells_dict["tetra"]  # Extract tetrahedra

    # Convert elements to edges (each triangle/tetrahedron defines connections)
    edges = np.hstack([
            [elements[:, 0], elements[:, 1]],  # Edge 1
            [elements[:, 0], elements[:, 2]],  # Edge 2
            [elements[:, 0], elements[:, 3]],  # Edge 3
            [elements[:, 1], elements[:, 2]],  # Edge 4
            [elements[:, 1], elements[:, 3]],  # Edge 5
            [elements[:, 2], elements[:, 3]],  # Edge 6
        ]).T # Shape: (num_edges, 2)

    edges = np.unique(edges, axis=0)  # Remove duplicate edges
    edge_index = torch.tensor(edges.T, dtype=torch.long)  # PyG format (2, num_edges)

    # Compute edge features (relative positions)
    edge_attr = node_positions[edges[:, 1]] - node_positions[edges[:, 0]]  # Shape: (num_edges, 3)
    edge_attr = torch.tensor(edge_attr, dtype=torch.float)
    return edge_index, edge_attr

In [150]:
# we will train the model with times t-2 and t-1 to predict t
# for each point, we can predict vx, vy, vz and p using the previous time steps of the neighbors (vx, vy, vz, p and distance)

# structure of the data : 
# data = {
#     'matrix' : [ # size N x 7
#         [x, y, z, vx, vy, vz, p],
#         [x, y, z, vx, vy, vz, p],
#         ...
#     ],
#     'target' : [ # size N x 4
#         [vx, vy, vz, p],
#         [vx, vy, vz, p],
#         ...
#     ]
#      'adjacency_matrix' : Matrix # size N x N
# }

def build_data():
    data = {
        'features' : [],
        'target' : []
    }
    list_files = os.listdir(osp.join(os.getcwd(), "4Students_AnXplore03"))
    list_files = [f for f in list_files if f.endswith('.xdmf')]

    for f in tqdm.tqdm(list_files[:3]):
        # print("\n\n New file:\n")
        xdmf_path = osp.join(os.getcwd(), "4Students_AnXplore03", f)
        meshes = xdmf_to_meshes(xdmf_path)
        mesh = meshes[0]

        edge_index, edge_attr = get_geometric_data(mesh)

        for time_step in range(2, len(meshes)):
            # Create node features (x, y, z, vx, vy, vz, p)
            node_features_1 = np.hstack([
                meshes[time_step-1].points,
                meshes[time_step-1].point_data['Vitesse'],
                meshes[time_step-1].point_data['Pression'].reshape(-1, 1)
            ]) # Shape: (num_nodes, 7)
            node_features = np.hstack([
                meshes[time_step].points,
                meshes[time_step].point_data['Vitesse'],
                meshes[time_step].point_data['Pression'].reshape(-1, 1)
            ]) # Shape: (num_nodes, 7)

            # Create PyTorch Geometric data object
            graph_data_1 = Data(x=node_features_1, edge_index=edge_index, edge_attr=edge_attr)
            graph_data = Data(x=node_features, edge_index=edge_index, edge_attr=edge_attr)

            data['features'].append(graph_data_1)
            data['target'].append(graph_data)
    return data

In [151]:
data = build_data()

  0%|          | 0/3 [00:00<?, ?it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\4Students_AnXplore03\AllFields_Resultats_MESH_1.xdmf



 33%|███▎      | 1/3 [00:00<00:00,  2.05it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\4Students_AnXplore03\AllFields_Resultats_MESH_11.xdmf



 67%|██████▋   | 2/3 [00:01<00:00,  1.33it/s]

Loaded 80 timesteps from c:\Users\alexi\Documents\mines\S5\idsc\data challenge janvier\demo\4Students_AnXplore03\AllFields_Resultats_MESH_117.xdmf



100%|██████████| 3/3 [00:02<00:00,  1.38it/s]


In [119]:
data['features'][0]

(11446, 7)

In [120]:
data['target'][0]

(11446, 4)

In [121]:
data.keys()

dict_keys(['matrix_t-1', 'target', 'adjacency_matrix'])

In [122]:
# get length of the data
len(data['features'])

234

# Message passing model

In [ ]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import MessagePassing
from torch_geometric.utils import add_self_loops

class FluidGNNLayer(MessagePassing):
    def __init__(self, in_channels, out_channels):
        super(FluidGNNLayer, self).__init__(aggr='mean')  # Mean aggregation
        self.edge_mlp = torch.nn.Sequential(
            torch.nn.Linear(in_channels * 2 + 3, 64),  # Edge MLP (uses node features + relative position)
            torch.nn.ReLU(),
            torch.nn.Linear(64, out_channels)
        )
        self.node_mlp = torch.nn.Sequential(
            torch.nn.Linear(in_channels + out_channels, 64),
            torch.nn.ReLU(),
            torch.nn.Linear(64, out_channels)
        )

    def forward(self, x, edge_index, edge_attr):
        """
        x: Node features (velocities, pressure, positions) [num_nodes, in_channels]
        edge_index: Connectivity [2, num_edges]
        edge_attr: Edge features (relative positions) [num_edges, 3]
        """
        edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        return self.propagate(edge_index, x=x, edge_attr=edge_attr)

    def message(self, x_i, x_j, edge_attr):
        """Message function: Computes messages from neighbors."""
        return self.edge_mlp(torch.cat([x_i, x_j, edge_attr], dim=1))

    def update(self, aggr_out, x):
        """Update function: Combines node's previous state with aggregated messages."""
        return self.node_mlp(torch.cat([x, aggr_out], dim=1))


In [ ]:
class FluidGNN(torch.nn.Module):
    def __init__(self, node_features, hidden_dim, output_dim):
        super(FluidGNN, self).__init__()
        self.gnn1 = FluidGNNLayer(node_features, hidden_dim)
        self.gnn2 = FluidGNNLayer(hidden_dim, hidden_dim)
        self.gnn3 = FluidGNNLayer(hidden_dim, output_dim)

    def forward(self, x, edge_index, edge_attr):
        x = F.relu(self.gnn1(x, edge_index, edge_attr))
        x = F.relu(self.gnn2(x, edge_index, edge_attr))
        x = self.gnn3(x, edge_index, edge_attr)  # Output velocity + pressure
        return x


In [ ]:
from torch_geometric.data import Data

# Example data (replace with your real mesh data)
num_nodes = 100
node_features = 7  # [vx, vy, vz, p, x, y, z]
edge_index = torch.randint(0, num_nodes, (2, 300))  # Random edges
x = torch.randn((num_nodes, node_features))  # Random node features
edge_attr = torch.randn((edge_index.size(1), 3))  # Random edge features

# Create PyTorch Geometric data object
graph_data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr)


In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Initialize model
model = FluidGNN(node_features=7, hidden_dim=64, output_dim=4)  # Output: vx, vy, vz, p
model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = torch.nn.MSELoss()

# Training loop
num_epochs = 100
for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()

    # Forward pass
    x_pred = model(graph_data.x.to(device), graph_data.edge_index.to(device), graph_data.edge_attr.to(device))

    # Compute loss (MSE between predicted and true values)
    loss = criterion(x_pred, graph_data.x[:, :4].to(device))  # Target: vx, vy, vz, p

    loss.backward()
    optimizer.step()

    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item():.4f}")
